name = deepcaves
author = Opons1
title = Deep Caves
depends = default
optional_depends = stairs, replacer, techage, moreores, technic, blox, terumet, gs_amethyst, gs_sapphire, gs_ruby, gs_emerald, lapis, quartz